'use strict';
const $=id=>document.getElementById(id);
const names=['Пион · дыхание','Тюльпан · колокол','Хризантема · хор','Лилия · сияние','Ромашка · ручей','Орхидея · эхо','Пион · лепесток','Лилия · роса','Орхидея · сон','Орхидея · свет','Дыхание сада','Туман','Пение воды','Звёздная пыль'];
const pitches=[60,64,67,72,74,79,62,76,57,69,48,55,67,81];
const sampleKeys=['air-ah','light-ee','nymph-choir','light-ee','water-oo','air-ah','air-ah','light-ee','water-oo','nymph-choir','air-ah','water-oo','water-oo','light-ee'];
const channels=names.map((name,i)=>({name,pitch:pitches[i],sample:sampleKeys[i],type:i%4,active:false,level:i<10?.35:.22,pan:(i%5-2)*.22,cutoff:i%4===3?1900:3100,reverb:.35+(i%3)*.08,delay:.12+(i%3)*.07,mute:false}));
const sliderValues=[.22,.64,.2,.82];let audio,master,buses=[],pack=new Map(),loadTask,playing=false,queue=Promise.resolve();const sources=new Map();
function range(i,key,label,min,max,step){return `<label><span>${label}<output id="out-${i}-${key}"></output></span><input id="ch-${i}-${key}" data-channel="${i}" data-param="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${channels[i][key]}"></label>`;}
const chainNames=['Фильтр → Reverb','Фильтр → Delay → Reverb','Фильтр → Chorus → Reverb','Фильтр → мягкое насыщение → Delay → Reverb'];
channels.forEach((ch,i)=>{const block=document.createElement('section');block.className='channel';block.innerHTML=`<h2>${String(i+1).padStart(2,'0')} / ${ch.name}</h2><div class="chain">${chainNames[ch.type]} → Pan / Level → Master</div><div class="channel-controls">${range(i,'level','LEVEL',0,1,.01)+range(i,'pan','PAN',-1,1,.01)+range(i,'cutoff','FILTER',200,8000,10)+range(i,'reverb','REVERB WET',0,.8,.01)+(ch.type===1||ch.type===3?range(i,'delay','DELAY WET',0,.65,.01):'')}</div><button class="mute" data-mute="${i}" aria-pressed="false">Mute</button>`;$('channels').appendChild(block);});
function status(){const n=channels.filter(c=>c.active).length;$('status').textContent=(playing?'Играет':'Выбрано')+' слоёв: '+n+(playing?'':' · нажми start');$('start').setAttribute('aria-pressed',String(playing));$('shape-164').setAttribute('fill',playing?'#f27291':'#FBFFB3');$('shape-165').setAttribute('fill',playing?'#1A3F6F':'#A32857');$('pause').disabled=!playing;}
function paintFlower(i){const group=$('flower-'+i);group.querySelectorAll('[fill]').forEach(node=>{if(!node.dataset.originalFill)node.dataset.originalFill=node.getAttribute('fill');if(node.dataset.originalFill.toUpperCase()==='#1A3F6F')node.setAttribute('fill',channels[i].active?'#f27291':'#1A3F6F');});document.querySelector(`[data-flower="${i}"]`).setAttribute('aria-pressed',String(channels[i].active));}
function toggleFlower(i){channels[i].active=!channels[i].active;paintFlower(i);if(playing){if(channels[i].active)startSource(i);else releaseSource(i);}status();}
document.querySelectorAll('[data-flower]').forEach(button=>button.addEventListener('click',()=>toggleFlower(Number(button.dataset.flower))));
function slider(i,value){sliderValues[i]=value;channels[10+i].active=value>.005;channels[10+i].sliderLevel=value;
 const handle=$('handle-'+i);const positions=[{y:721-441*value,origin:626},{y:856-363*value,origin:626},{x:934+441*value,origin:1021.5},{x:934+441*value,origin:1297}];const pos=positions[i];handle.setAttribute('transform',pos.x!==undefined?`translate(${pos.x-pos.origin} 0)`:`translate(0 ${pos.y-pos.origin})`);
 if(playing){if(channels[10+i].active)startSource(10+i);else releaseSource(10+i);}applyChannel(10+i);status();}
for(let i=0;i<4;i++){$('slider-'+i).value=sliderValues[i];$('slider-'+i).addEventListener('input',()=>slider(i,Number($('slider-'+i).value)));slider(i,sliderValues[i]);}
function param(p,v){p.setTargetAtTime(v,audio.currentTime,.07);}
function impulse(){const n=Math.floor(audio.sampleRate*3),buf=audio.createBuffer(2,n,audio.sampleRate);for(let c=0;c<2;c++){const d=buf.getChannelData(c);for(let j=0;j<n;j++)d[j]=(Math.random()*2-1)*Math.pow(1-j/n,3.5);}return buf;}
function buildBus(i,ir){const ch=channels[i],input=audio.createGain(),filter=audio.createBiquadFilter();filter.type='lowpass';input.connect(filter);let output=filter;const b={input,filter};
 if(ch.type===3){const shaper=audio.createWaveShaper(),curve=new Float32Array(1024);for(let j=0;j<1024;j++){const x=j/1023*2-1;curve[j]=Math.tanh(x*1.4)/Math.tanh(1.4);}shaper.curve=curve;shaper.oversample='2x';output.connect(shaper);output=shaper;}
 if(ch.type===1||ch.type===3){const delay=audio.createDelay(1),feedback=audio.createGain(),sum=audio.createGain(),dry=audio.createGain(),wet=audio.createGain();delay.delayTime.value=.28+(i%3)*.12;feedback.gain.value=.2;output.connect(dry);dry.connect(sum);output.connect(delay);delay.connect(wet);wet.connect(sum);delay.connect(feedback);feedback.connect(delay);b.delayDry=dry;b.delayWet=wet;output=sum;}
 if(ch.type===2){const delay=audio.createDelay(.1),lfo=audio.createOscillator(),depth=audio.createGain(),sum=audio.createGain(),wet=audio.createGain();delay.delayTime.value=.018;lfo.frequency.value=.17+(i%3)*.08;depth.gain.value=.004;lfo.connect(depth);depth.connect(delay.delayTime);output.connect(sum);output.connect(delay);delay.connect(wet);wet.gain.value=.3;wet.connect(sum);lfo.start();b.lfo=lfo;output=sum;}
 const convolver=audio.createConvolver(),dry=audio.createGain(),wet=audio.createGain(),sum=audio.createGain();convolver.buffer=ir;output.connect(dry);dry.connect(sum);output.connect(convolver);convolver.connect(wet);wet.connect(sum);
 b.reverbDry=dry;b.reverbWet=wet;b.pan=audio.createStereoPanner();b.gain=audio.createGain();sum.connect(b.pan);b.pan.connect(b.gain);b.gain.connect(master);return b;}
async function init(){if(!audio){const Context=window.AudioContext||window.webkitAudioContext;if(!Context)throw Error('Web Audio не поддерживается');audio=new Context();master=audio.createGain();const compressor=audio.createDynamicsCompressor();compressor.threshold.value=-18;compressor.knee.value=18;compressor.ratio.value=8;master.connect(compressor);compressor.connect(audio.destination);master.gain.value=Number($('master').value)*.45;const ir=impulse();buses=channels.map((_,i)=>buildBus(i,ir));channels.forEach((_,i)=>applyChannel(i));}
 if(!loadTask)loadTask=Promise.all(Object.entries(window.NYMPH_SAMPLES).map(async([key,s])=>{const binary=atob(s.data),bytes=new Uint8Array(binary.length);for(let j=0;j<binary.length;j++)bytes[j]=binary.charCodeAt(j);pack.set(key,await audio.decodeAudioData(bytes.buffer));})).catch(e=>{loadTask=null;throw e;});await loadTask;}
function transport(action){queue=queue.catch(()=>{}).then(async()=>{try{if(action==='start'){await init();await audio.resume();playing=audio.state==='running';if(playing)channels.forEach((ch,i)=>{if(ch.active)startSource(i);});}else{playing=false;if(audio)await audio.suspend();}status();}catch(e){playing=false;status();$('status').textContent='Не удалось включить звук: '+e.message;console.error(e);}});return queue;}
function startSource(i){if(sources.has(i)||!pack.has(channels[i].sample))return;const ch=channels[i],source=audio.createBufferSource(),gain=audio.createGain(),now=audio.currentTime;source.buffer=pack.get(ch.sample);source.loop=true;source.playbackRate.value=Math.pow(2,(ch.pitch-57)/12);source.detune.value=(i%3-1)*4;gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.62,now+.65+(i%3)*.2);source.connect(gain);gain.connect(buses[i].input);source.start();sources.set(i,{source,gain});}
function releaseSource(i){const v=sources.get(i);if(!v)return;sources.delete(i);const now=audio.currentTime;if(v.gain.gain.cancelAndHoldAtTime)v.gain.gain.cancelAndHoldAtTime(now);else{v.gain.gain.cancelScheduledValues(now);v.gain.gain.setValueAtTime(.62,now);}v.gain.gain.linearRampToValueAtTime(0,now+1.4);v.source.stop(now+1.45);v.source.onended=()=>{v.source.disconnect();v.gain.disconnect();};}
function applyChannel(i){const ch=channels[i],b=buses[i];for(const key of ['level','pan','cutoff','reverb','delay']){const o=$('out-'+i+'-'+key);if(o)o.textContent=key==='cutoff'?Math.round(ch[key])+' Hz':key==='pan'?ch[key].toFixed(2):Math.round(ch[key]*100)+'%';}if(!b)return;param(b.filter.frequency,ch.cutoff);param(b.filter.Q,.45);param(b.pan.pan,ch.pan);param(b.gain.gain,ch.mute?0:ch.level*(i<10?1:ch.sliderLevel));param(b.reverbDry.gain,1-ch.reverb);param(b.reverbWet.gain,ch.reverb);if(b.delayWet){param(b.delayDry.gain,1-ch.delay);param(b.delayWet.gain,ch.delay);}}
document.querySelectorAll('[data-param]').forEach(input=>input.addEventListener('input',()=>{const i=Number(input.dataset.channel);channels[i][input.dataset.param]=Number(input.value);applyChannel(i);}));
document.querySelectorAll('[data-mute]').forEach(button=>button.addEventListener('click',()=>{const i=Number(button.dataset.mute);channels[i].mute=!channels[i].mute;button.setAttribute('aria-pressed',String(channels[i].mute));applyChannel(i);}));
$('master').addEventListener('input',()=>{if(master)param(master.gain,Number($('master').value)*.45);});$('start').addEventListener('click',()=>transport('start'));$('pause').addEventListener('click',()=>transport('pause'));
$('clear').addEventListener('click',()=>{for(let i=0;i<10;i++){channels[i].active=false;paintFlower(i);releaseSource(i);}status();});
const heldKeys=new Set();document.addEventListener('keydown',e=>{if(['INPUT','BUTTON','TEXTAREA'].includes(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;const i='1234567890'.indexOf(e.key);if(i>=0){e.preventDefault();if(!e.repeat&&!heldKeys.has(e.key)){heldKeys.add(e.key);toggleFlower(i);}}});document.addEventListener('keyup',e=>heldKeys.delete(e.key));window.addEventListener('blur',()=>heldKeys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)transport('pause');});channels.forEach((_,i)=>applyChannel(i));status();
